\echo info--   start batch deploy of scaffolding
\echo info--
\set ON_ERROR_STOP on
\set VERBOSITY verbose
\timing on

\echo info-- Creating elements at destination database
\i sql_scripts/schema_creation.sql

\i sql_scripts/accounting/tables/account_types.sql
\i sql_scripts/accounting/tables/entry_types.sql
\i sql_scripts/accounting/tables/transactions.sql
\i sql_scripts/accounting/tables/accounts.sql
\i sql_scripts/accounting/tables/ledger_entries.sql

-----------------------------------------------------------
\echo info-- Granting user permissions
SELECT (current_database() like '%dev%') AS is_dev_db \gset
\if :is_dev_db
    \echo info-- granting permission user for dev environment
    \i sql_scripts/accounting/permissions/dev.sql
\endif

SELECT (current_database() like '%test%') AS is_test_db \gset
\if :is_test_db
    \echo info-- granting permission user for test environment
    \i sql_scripts/accounting/permissions/test.sql
\endif

SELECT (current_database() like '%prod%') AS is_prod_db \gset
\if :is_prod_db
    \echo info-- granting permission user for prod environment
    \i sql_scripts/accounting/permissions/prod.sql
\endif

\echo info--   run