#name: Pytest tests execution
#
#on:
#  pull_request:
#    branches:
#      - dev
#      - main
#  push:
#    branches:
#      - dev
#      - main
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f env/requirements.txt ]; then pip install -r env/requirements.txt; fi
#      - name: Test with pytest
#        env:
#          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
#          PASSWORD: ${{ secrets.PASSWORD_TEST }}
#          SECRET_KEY: ${{ secrets.SECRET_KEY_TEST }}
#          USER: ${{ secrets.USER_TEST }}
#        run: |
#          python -m pytest -vv
